name: ScannedReceipt-fastapi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - fastapi==0.120.4
      - uvicorn==0.38.0
      - pillow==12.0.0
      - ultralytics==8.3.223
      - ultralytics-thop==2.0.18
      - pydantic-settings==2.11.0
      - python-multipart==0.0.20
      - gdown==5.2.0
      - pandas==2.3.2
